In [2]:
import numpy as np

Dadas as matrizes e equações abaixo:

$$
A = \begin{bmatrix} 1 & 7\\ 3 & 2 \end{bmatrix} \\
$$

$$
B = \begin{bmatrix} 4 & 9\\ 8 & 2 \end{bmatrix} \\
$$

$$
C = AB \\
$$

$$
D = BA 
$$

$$
ABXDD^{-1} = CDBAD^{-1}
$$

responda:

A. Qual é o valor de $X$?

In [9]:
a = np.array([[1,7],[3,2]])
b = np.array([[4,9],[8,2]])
c = a @ b
d = b @ a

x = b @ a
x

array([[31, 46],
       [14, 60]])

V = BW

V -> Estou representando de uma forma e vou querer começar a passar de outra forma (Receita)

B -> Matriz com vários pontos que quero passar o V (Base de dados)

W -> Ponto onde o V vai parar

Suponha que você é um gerente de uma pizzaria e tem os seguintes dados sobre seus ingredientes e vendas de pizzas:

- Cada pizza de queijo requer 2 xícaras de queijo e 1 xícara de molho de tomate.
- Cada pizza de pepperoni requer 1 xícara de queijo, 1 xícara de molho de tomate e 0,5 xícara de pepperoni.
- Cada pizza vegetariana requer 1 xícara de queijo, 1 xícara de molho de tomate e 1 xícara de legumes.
- Cada pizza completa requer 1 xícara de queijo, 1 xícara de molho de tomate, 0,5 xícara de pepperoni e 0,5 xícara de legumes.

*Usando estritamente formulações matriciais*, responda:

Quantas pizzas de cada tipo devem ser vendidas para utilizar todo o estoque de ingredientes abaixo?

- 71 xícaras de queijo
- 52 xícaras de molho de tomate
- 10 xícaras de pepperoni
- 17 xícaras de legumes

Se você vendesse uma pizza de queijo por R$10, uma pizza de pepperoni por R$12, uma pizza vegetariana por R$15 e uma pizza completa por R$20, qual seria o valor total das vendas?


In [4]:
# V = BW
# V -> Estou representando de uma forma e vou querer começar a passar de outra forma (Receita)
# B -> Matriz com vários pontos que quero passar o V (Base de dados)
# W -> Ponto onde o V vai parar

pizza_queijo = np.array([2,1,0,0])
pizza_pepperoni = np.array([1,1,0.5,0])
pizza_vegetariana = np.array([1,1,0,1])
pizza_completa = np.array([1,1,0.5,0.5])

ingredientes = np.array([71, 52, 10, 17]).T # V

pizzas = np.vstack((pizza_queijo, pizza_pepperoni, pizza_vegetariana, pizza_completa)).T #B

w = np.linalg.inv(pizzas) @ ingredientes
print(w)

valores = np.array([10,12,15,20])

total = w @ valores
print(total)

[19. 12. 13.  8.]
689.0


# Exercício 5

Escreva o vetor $x$ tal que:

$$
\begin{bmatrix} -5 \\ 3 \end{bmatrix} = \begin{bmatrix} 0 & 1\\ 2 & 3 \end{bmatrix} x
$$

In [5]:
a = np.array([[-5],[3]])

b = np.array([[0,1],[2,3]])

x = np.linalg.inv(b) @ a
x


array([[ 9.],
       [-5.]])

# Exercício 3

Quatro amigos foram a uma lanchonete, e fizeram os seguintes pedidos:

* 1 x-salada e 1 suco de laranja, no total de R$10,00,
* 2 x-salada e 2 suco de laranja, no total de R$20,00,
* 2 x-salada e 1 suco de laranja, no total de R$13,00,
* 4 x-salada e 2 suco de laranja, no total de R$26,00.


1. Qual é o preço do x-salada?
1. Qual é o preço do suco de laranja?
1. Qual é o valor de uma compra de 1 x-salada e 2 sucos de laranja?


In [4]:
# V = BW

b = np.array( [[1, 1],[2, 1]]) #B
v = np.array( [[10],[13]]) #V

w = np.linalg.inv(b) @ v

print(w)
# 3
compra = np.array( [[1, 2]]) @ w
print(compra)

[[3.]
 [7.]]
[[17.]]


Algumas carteiras de investimento deram os seguintes retornos:

* 100 ações da empresa E1 e 200 ações da E2 deram retorno de R$100,00,
* 1000 ações da empresa E1 e 2000 ações da E2 deram retorno de R$1000,00,
* 200 ações da empresa E2 e 300 da E3 deram retorno de R$500,00 
* 400 ações da empresa E2 e 600 da E3 deram retorno de R$1000,00 
* 1000 ações da empresa E1 e 100 da E3 deram retorno de R$1500,00
* 2000 ações da empresa E1 e 200 da E3 deram retorno de R$3000,00 

*Usando estritamente formulações matriciais*, responda:
1. Qual é o retorno por ação de cada empresa?
1. Qual é o retorno de uma carteira com 100 ações da empresa E1, 200 da empresa E2 e 300 da E3?

________________________________________________________________________________________________________

In [15]:
acoes1 = np.array([100,200,0])
acoes2 = np.array([0,200,300])
acoes3 = np.array([1000,0,100])

acoes = np.vstack((acoes1, acoes2, acoes3))

retorno = np.array([100,500,1500])

x = np.linalg.inv(acoes) @ retorno

quantidade = np.array([100,200,300])

resultado = x @ quantidade
resultado



632.258064516129